### ISSUE TITLE
Rethink dependency structure

### ISSUE THREAD

**Issue by btjanaka** [icaros-usc/pyribs#133]
Currently, we are telling users to `pip install ribs[all]`, but this is more confusing than just `pip install ribs`. Perhaps we can just have `ribs` be the main thing we tell people to install, and `ribs[visualize]` and other things can be extras. After all, they are called "extras" ;)

This would be similar to what libraries like [OpenAI gym](https://github.com/openai/gym/blob/master/setup.py#L9) and [Deepmind acme](https://github.com/deepmind/acme) do.

## TODO

- [x] Edit structure in setup.py - #183
- [x] Update the structure of the GitHub Actions tests - #183
- [x] Modify the conda packages accordingly - let's start using extras just like gym does https://github.com/conda-forge/gym-feedstock/blob/master/recipe/meta.yaml
  - Here is a bit more context https://github.com/conda-forge/filesystem-spec-feedstock/issues/60
- [x] Create new installation selector -- implement in JS -> Divert to pyribs.org repo

**Comment by btjanaka** [comment]
This is implemented in pyribs v0.5.0. The Conda packages will be available shortly.
