### ISSUE TITLE
[FEATURE REQUEST] Diversity Optimization

### ISSUE THREAD

**Issue by btjanaka** [icaros-usc/pyribs#474]
### Description

Issue to track progress of diversity optimization implementation in pyribs.

General:

- [x] Modify the scheduler API to support diversity optimization -> #473

Emitters:

- [x] Modify all emitters to support diversity optimization (i.e., objective should be allowed to be None)
    - All but GradientArborescenceEmitter will work. Getting GradientArborescenceEmitter to work may not be straightforward.
- [x] Add a NoveltyRanker -> #477 
- [x] Add NSLCRanker -> Diverted to #544

Novelty Search:

- [x] Add ProximityArchive -> #472, #468
- [x] Add visualization tool -> #476
- [x] Add novelty search to sphere.py -> #478
- [x] Add local competition to ProximityArchive -> #481
    - Requires considering nearest neighbor behavior -> if solution is below threshold, compare it to nearest neighbor and replace the nearest neighbor if it has a better objective
    - Can be turned on with a `local_competition` flag
    - Objective should be required to be passed in when using local competition behavior

DDS:

- [x] Add ranker -> #483
  - [x] Update ranker -- it cannot call `compute_density` because that is rather inefficient. Instead, the archive should just return the density in `add` -> #504
- [x] Add archive -> #487
- [x] Add DDS to sphere.py -> #487
- [x] Try DDS with sklearn kernel density
- [x] Diverted to #545

**Comment by gresavage** [comment]
@btjanaka FYI  I'm working on the Novelty and NSLC rankers right now.

**Comment by btjanaka** [comment]
Sounds good; let's put those in a separate PR. By the way, would you like to meet sometime? Perhaps we can chat a bit about pyribs and these things especially since we've greatly expanded the scope beyond your original request. You can reach out to me on the pyribs Discord (https://discord.gg/QxhcJSqZ8G -- I'm username btjanaka) or over email (tjanaka@usc.edu)

**Comment by btjanaka** [comment]
@gresavage I talked with Matt Fontaine in our lab, and we agree your original approach to local competition makes sense. It just seems strange that there is no documentation of it in the NSLC paper. Roughly, if a solution is below the novelty threshold, we should compare its objective to its nearest neighbor and replace if necessary. I'll work on putting that back in.
